version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "06:00"
      timezone: "Europe/Amsterdam"
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"
    commit-message:
      prefix: "chore(actions)"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "06:15"
      timezone: "Europe/Amsterdam"
    open-pull-requests-limit: 5
    groups:
      go-modules:
        patterns:
          - "*"
    commit-message:
      prefix: "chore(go)"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "06:30"
      timezone: "Europe/Amsterdam"
    open-pull-requests-limit: 5
    groups:
      docker-images:
        patterns:
          - "*"
    commit-message:
      prefix: "chore(docker)"
